### ISSUE TITLE
Executable permission not preserved since update to 1.4.0

### ISSUE THREAD

**Issue by vmkalbskopf** [vukbgit/ftp-remote-edit-plus#12]
When editing a script on the remote server (linux) using this module on my laptop (mac os), the execution permission of the file is not preserved.
I have tested this by creating a new file on the  server (using vim) and making it executable. Then I edit the file using atom. The executable permission is lost.

I have tried deleting the server. I am also using the same user on the server and in the server settings.

I have changed the file attribute settings using the dialog provided by the package. But as soon as I save the file, it changes back to this:

<img width="528" alt="Screenshot 2021-09-27 at 11 07 11" src="https://user-images.githubusercontent.com/22935643/134879110-2e089a9b-ab07-4629-8c53-a971a5a02226.png">

I have tried putting in `x`s but it throws this error:

````
Uncaught TypeError: Cannot read property 'other' of undefined

/Users/victor/.atom/packages/ftp-remote-edit-plus/lib/helper/format.js:208
Hide Stack Trace
TypeError: Cannot read property 'other' of undefined
    at permissionsToRights (/Users/victor/.atom/packages/ftp-remote-edit-plus/lib/helper/format.js:208:32)
    at PermissionsView.updateCheckboxInputs (/Users/victor/.atom/packages/ftp-remote-edit-plus/lib/views/permissions-view.js:513:18)
    at /Users/victor/.atom/packages/ftp-remote-edit-plus/lib/views/permissions-view.js:145:12
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1186925)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1188366)
    at TextBuffer.emitDidChangeTextEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:507940)
    at TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:495895)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:26664)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:18599
    at TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:41978)
    at TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:41487)
    at TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:18562)
    at TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:18111)
    at TextEditorComponent.didTextInput (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:96704)
````

**Comment by vukbgit** [comment]
Hello, I digged a bit into it and it seems related to the SSH/SFTP library not returning files permission anymore, so the library defaults back to 644.  I had to update the dependency version recently due to a [security issue](https://github.com/advisories/GHSA-652h-xwhf-q4h6) of the library and I am now facing some troubles. I'll try to work it out again but I can't promise anything...any help appreciated!

**Comment by vmkalbskopf** [comment]
Oh man! That sounds very frustrating. Unfortunately I don't have any experience with this, so I can't help.
I'll just add a permission change when I am executing the script server side. A hack, but good enough for now.

**Comment by vmkalbskopf** [comment]
I submitted a bug here:
https://github.com/mscdex/ssh2/issues/1073

Is that useful?

**Comment by vukbgit** [comment]
well we'll discover soon, I'll try to add asap some technical context to your issue

**Comment by vmkalbskopf** [comment]
Sorry for jumping ahead of you :-|

**Comment by vukbgit** [comment]
no problem. I just tested the [original package](https://atom.io/packages/ftp-remote-edit) and:

- it requires ssh2 0.8.9 (instead of the last 1.4.0)
- file permissions are kept on saving (so your issue is not happening)
- connection via sftp is faster; in my experience, since updating ssh2, my package has become much more slower

Of course if you switch to [ftp-remote-edit](https://atom.io/packages/ftp-remote-edit) you wont have the benefit of folders anymore, your choice!

**Comment by vmkalbskopf** [comment]
Yes, I've noticed the slow-down as well.
I guess the api has changed a lot. Good luck my friend!
